"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, LockKeyhole, Mail, Phone, UserRound } from "lucide-react";
import { taoSupabaseTrinhDuyet } from "@/lib/supabase/client";
export type CheDo="dang_nhap"|"dang_ky";
function dich(){if(typeof window==="undefined")return "/";const n=new URLSearchParams(window.location.search).get("next")||"/";return n.startsWith("/")&&!n.startsWith("//")?n:"/";}
function callback(next:string){return `${window.location.origin}/xac-thuc?next=${encodeURIComponent(next)}`;}
function matKhauTot(v:string){return v.length>=8&&/[A-Za-zÀ-ỹ]/.test(v)&&/\d/.test(v);}
export function AuthForm({cheDo}: {cheDo:CheDo}){const [ten,setTen]=useState("");const [sdt,setSdt]=useState("");const [email,setEmail]=useState("");const [mk,setMk]=useState("");const [xacNhan,setXacNhan]=useState("");const [dang,setDang]=useState(false);const [tb,setTb]=useState<string|null>(null);useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("loi")==="xac-thuc")setTb("Không thể hoàn tất xác thực. Liên kết có thể đã hết hạn hoặc quá trình đăng nhập đã bị hủy.");},[]);
const xaHoi=async(provider:"google"|"facebook")=>{const s=taoSupabaseTrinhDuyet();if(!s)return setTb("Hệ thống đăng nhập chưa được cấu hình.");setDang(true);const {error}=await s.auth.signInWithOAuth({provider,options:{redirectTo:callback(dich())}});if(error){setDang(false);setTb("Không thể kết nối phương thức đăng nhập này lúc này.");}};
const gui=async(e:FormEvent)=>{e.preventDefault();const s=taoSupabaseTrinhDuyet();if(!s)return setTb("Hệ thống đăng nhập chưa được cấu hình.");const mail=email.trim().toLowerCase();if(!matKhauTot(mk))return setTb("Mật khẩu phải có ít nhất 8 ký tự, có chữ và số.");setDang(true);setTb(null);if(cheDo==="dang_nhap"){const {error}=await s.auth.signInWithPassword({email:mail,password:mk});setDang(false);if(error)return setTb("Email hoặc mật khẩu chưa chính xác, hoặc email chưa được xác thực.");window.location.href=dich();return;}if(ten.trim().length<2){setDang(false);return setTb("Vui lòng nhập họ và tên.");}if(mk!==xacNhan){setDang(false);return setTb("Mật khẩu xác nhận chưa khớp.");}const {data,error}=await s.auth.signUp({email:mail,password:mk,options:{emailRedirectTo:callback(dich()),data:{full_name:ten.trim(),phone:sdt.trim()||null}}});setDang(false);if(error)return setTb("Không thể tạo tài khoản lúc này. Vui lòng kiểm tra thông tin và thử lại.");if(data.session){window.location.href=dich();return;}setTb("Yêu cầu tạo tài khoản đã được tiếp nhận. Hãy kiểm tra email để xác thực tài khoản.");};
const dk=cheDo==="dang_ky";return <div className="the-form"><span className="nhan">BÁN GÌ AI</span><h1>{dk?"Tạo tài khoản":"Đăng nhập"}</h1><p>{dk?"Tạo tài khoản để đồng bộ sản phẩm đã lưu, quá trình thử nghiệm và hồ sơ bán hàng.":"Đăng nhập để tiếp tục sử dụng dữ liệu của riêng bạn."}</p><div className="mang-xa-hoi"><button className="nut-phu" disabled={dang} onClick={()=>xaHoi("google")}>Đăng nhập bằng Google</button><button className="nut-phu" disabled={dang} onClick={()=>xaHoi("facebook")}>Đăng nhập bằng Facebook</button></div><div className="chia">hoặc dùng email và mật khẩu</div><form className="bieu-mau" onSubmit={gui}>{dk&&<><label>Họ và tên<div className="hang"><UserRound size={18}/><input required value={ten} onChange={e=>setTen(e.target.value)} /></div></label><label>Số điện thoại<div className="hang"><Phone size={18}/><input inputMode="tel" value={sdt} onChange={e=>setSdt(e.target.value)} /></div></label></>}<label>Email<div className="hang"><Mail size={18}/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></div></label><label>Mật khẩu<div className="hang"><LockKeyhole size={18}/><input type="password" required minLength={8} value={mk} onChange={e=>setMk(e.target.value)} /></div></label>{dk&&<label>Xác nhận mật khẩu<input type="password" required minLength={8} value={xacNhan} onChange={e=>setXacNhan(e.target.value)} /></label>} {!dk&&<div className="hang giua"><Link href="/quen-mat-khau">Quên mật khẩu?</Link></div>}<button className="nut-chinh" style={{width:"100%"}} disabled={dang}>{dang?"Đang xử lý…":dk?"Tạo tài khoản":"Đăng nhập"}<ArrowRight size={18}/></button></form>{tb&&<div className="thong-bao">{tb}</div>}<p style={{textAlign:"center"}}>{dk?<>Đã có tài khoản? <Link href="/dang-nhap">Đăng nhập</Link></>:<>Chưa có tài khoản? <Link href="/dang-ky">Tạo tài khoản</Link></>}</p></div>}
