import type { GoiTaiKhoan } from "@/lib/types";
export type YeuCauAI={huongDan:string;noiDung:string;soTokenToiDa?:number};
export type KetQuaAI={noiDung:string;nhaCungCap:"groq"|"gemini"|"openrouter"|"openai";dungBanTraPhi:boolean};
async function fetchHan(url:string,init:RequestInit,ms=20000){const c=new AbortController();const id=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal});}finally{clearTimeout(id);}}
function model(name:string){const v=process.env[name];if(!v)throw new Error("Mô hình AI chưa được cấu hình.");return v;}
async function chatCompat(url:string,key:string,modelName:string,y:YeuCauAI,headers:Record<string,string>={}){const r=await fetchHan(url,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json",...headers},body:JSON.stringify({model:modelName,messages:[{role:"system",content:y.huongDan},{role:"user",content:y.noiDung}],max_tokens:y.soTokenToiDa??900,temperature:.2})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Nhà cung cấp AI lỗi ${r.status}.`);const text=p?.choices?.[0]?.message?.content?.trim?.();if(!text)throw new Error("Nhà cung cấp AI không trả nội dung.");return text;}
async function groq(y:YeuCauAI):Promise<KetQuaAI>{const key=process.env.GROQ_API_KEY;if(!key)throw new Error("Groq chưa cấu hình.");return {noiDung:await chatCompat("https://api.groq.com/openai/v1/chat/completions",key,model("GROQ_MODEL"),y),nhaCungCap:"groq",dungBanTraPhi:false};}
async function openrouter(y:YeuCauAI):Promise<KetQuaAI>{const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error("OpenRouter chưa cấu hình.");return {noiDung:await chatCompat("https://openrouter.ai/api/v1/chat/completions",key,model("OPENROUTER_MODEL"),y,{"X-Title":"BÁN GÌ AI"}),nhaCungCap:"openrouter",dungBanTraPhi:false};}
async function gemini(y:YeuCauAI):Promise<KetQuaAI>{const key=process.env.GEMINI_API_KEY;if(!key)throw new Error("Gemini chưa cấu hình.");const m=model("GEMINI_MODEL");const r=await fetchHan(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:y.huongDan}]},contents:[{role:"user",parts:[{text:y.noiDung}]}],generationConfig:{temperature:.2,maxOutputTokens:y.soTokenToiDa??900}})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Gemini lỗi ${r.status}.`);const text=p?.candidates?.[0]?.content?.parts?.map((x:any)=>x?.text).filter((x:unknown)=>typeof x==="string").join("\n").trim();if(!text)throw new Error("Gemini không trả nội dung.");return {noiDung:text,nhaCungCap:"gemini",dungBanTraPhi:false};}
async function openai(y:YeuCauAI):Promise<KetQuaAI>{const key=process.env.OPENAI_API_KEY;if(!key)throw new Error("OpenAI chưa cấu hình.");const r=await fetchHan("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:model("OPENAI_MODEL"),instructions:y.huongDan,input:y.noiDung,max_output_tokens:y.soTokenToiDa??900})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`OpenAI lỗi ${r.status}.`);let text=typeof p?.output_text==="string"?p.output_text.trim():"";if(!text){const parts:string[]=[];for(const item of p?.output??[])for(const c of item?.content??[])if(c?.type==="output_text"&&typeof c.text==="string")parts.push(c.text);text=parts.join("\n").trim();}if(!text)throw new Error("OpenAI không trả nội dung.");return {noiDung:text,nhaCungCap:"openai",dungBanTraPhi:true};}
async function thu(ds:Array<()=>Promise<KetQuaAI>>){for(const fn of ds){try{return await fn();}catch(e){console.warn("Nhà cung cấp AI không khả dụng:",e instanceof Error?e.message:e);}}throw new Error("Không có dịch vụ AI nào khả dụng lúc này.");}
export async function taoPhanTichAI(y:YeuCauAI,goi:GoiTaiKhoan,choPhepTraPhi=false){if(goi==="vip")return thu([()=>openai(y),()=>groq(y),()=>gemini(y),()=>openrouter(y)]);const ds:Array<()=>Promise<KetQuaAI>>=[()=>groq(y),()=>gemini(y),()=>openrouter(y)];if(choPhepTraPhi)ds.push(()=>openai(y));return thu(ds);}
